[project]
name = "traj_interact_predict"
version = "0.0.1"
requires-python = ">=3.10"

[project.scripts]
train-traj-interact = "scripts.train:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
